[package]
name = "db65"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
rustyline = "13.0.0"
thiserror = "1.0.51"

[build-dependencies]
cc = "1.0.83"
